StdError = StandardError

def class Exception {

  def raise! {
    raise: ~[self]
  }

}
