StdError = StandardError

def class Exception {

  def raise! {
    ruby: 'raise args: [self]
  }

}
