try {
  "Empty catch" println
} catch StdError => e {
}
